export enum PagePath {
  LOGIN = "/login",
  REGISTER = "/register",
  VERIFY_EMAIL = "/verify-email",
  VERIFY_OTP = "/verify-otp",
  RESET_PASSWORD = "/reset-password",
  NOT_FOUND = "/404",
  HOME = "/home",
  USER_MANAGEMENT = "/user-management",
  USER_DETAIL = "/user-management/:id",
  BLOG_MANAGEMENT = "/blog-management",
  CAMP_MANAGEMENT = "/camp-management",
  CAMP = "/camp",
  CAMP_DETAIL = "/camp/:campId",
  BLOG = "/blog",
  BLOG_DETAIL = "/blog/:blogId",
  CHAT = "/chat",
  ANY = "*",
  FORBIDDEN = "/403",
  ROOT = "/",
  ABOUT = "/about",
  CONTACT = "/contact",
  FAQ = "/faq",
  REGISTER_SUCCESS = "/register-success/:registrationId",

  //User Routes
  USER_MYPROFILE = "/user/my-profile",
  USER_MYREGISTRATIONS = "/user/my-registrations",
  USER_MYREGISTRATIONS_DETAIL = "/user/my-registrations/:registrationId",
  USER_PAYMENT_HISTORY = "/user/payment-history",
  USER_PAYMENT_HISTORY_DETAIL = "/user/payment-history/:transactionId",
  USER_MYCAMPERS = "/user/my-campers",
  USER_CAMPER_DETAIL = "/user/my-campers/:camperId",
  USER_CAMPER_EDIT = "/user/my-campers/edit/:camperId",
  REGISTRATION_FORM = "/register-camp/:campId",



  // Admin Routes
  ADMIN_DASHBOARD = "/admin/dashboard",
  ADMIN_CAMPS = "/admin/camps",
  ADMIN_CAMPS_DETAIL = "/admin/camps/:campId",
  ADMIN_CAMPTYPES = "/admin/camp-types",
  ADMIN_BLOGS = "/admin/blogs",
  ADMIN_ACCOUNTS = "/admin/accounts",
  ADMIN_VEHICLES = "/admin/vehicles",
  ADMIN_VEHICLE_TYPES = "/admin/vehicle-types",
  ADMIN_SETTINGS = "/admin/settings",
  ADMIN_USERS = "/admin/users",
  ADMIN_FAQS = "/admin/faqs",
  ADMIN_TRANSACTIONS = "/admin/transactions",
  ADMIN_CALENDAR = "/admin/calendar",
  ADMIN_REPORTS = "/admin/reports",

  // Staff Routes
  STAFF_SCHEDULE = "/staff/schedule",
  STAFF_CAMPS = "/staff/camps",
  STAFF_BLOGS = "/staff/blogs",
  STAFF_ATTENDANCE = "/staff/attendance",
  STAFF_CALENDAR = "/staff/calendar",
  STAFF_PHOTOS = "/staff/photos",
  STAFF_CHECKIN = "/staff/checkin ",

  //Manager Routes
  MANAGER_DASHBOARD = "/manager/dashboard",
  MANAGER_REGIS = "/manager/registrations",
  MANAGER_CAMPERS = "/manager/campers",
  MANAGER_ACTIVITIES = "/manager/activities",
  MANAGER_GROUPS = "/manager/groups",
  MANAGER_TRANSPORTATION = "/manager/transportation",
  MANAGER_ACCOMODATION = "/manager/accomodation",
  MANAGER_PAYMENTS = "/manager/payments",
  MANAGER_CALENDAR = "/manager/calendar",
  MANAGER_INCIDENTS = "/manager/incidents",
  MANAGER_LOCATIONS = "/manager/locations",
  MANAGER_STAFFS = "/manager/staffs",

  //Driver Routes
  DRIVER_CALENDAR = "/driver/locations",
}
