export enum PagePath {
  LOGIN = "/Login",
  REGISTER = "/Register",
  VERIFY_EMAIL = "/VerifyEmail",
  VERIFY_OTP = "/VerifyOTP",
  RESET_PASSWORD = "/ResetPassword",
  NOT_FOUND = "/404",
  HOME = "/Home",
  USER_MANAGEMENT = "/UserManagement",
  USER_DETAIL = "/UserManagement/:id",
  BLOG_MANAGEMENT = "/BlogManagement",
  CAMP_MANAGEMENT = "/CampManagement",
  CAMP = "/Camp",
  CAMP_DETAIL = "/Camp/:campId",
  BLOG = "/Blog",
  BLOG_DETAIL = "/Blog/:blogId",
  CHAT = "/Chat",
  ANY = "*",
  FORBIDDEN = "/403",
  ROOT = "/",
}
